version: "3"
services:
  node:
      build: 
        context: .
        args: 
          - NODE=14.17.4
          - NODE_ENV=development
      environment: 
        - NODE_ENV=development
      ports:
        - 4200:4200
      volumes:
        - .:/opt/node_app/app
        - ./package.json:/opt/node_app/package.json
        - ./package-lock.json:/opt/node_app/package-lock.json